### ISSUE TITLE
build_static_name_table: AttributeError: 'NoneType' object has no attribute 'AxisValue'

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/axisregistry#156]
If I install `axisregistry v0.4.4` I get this ERROR (introduced by https://github.com/googlefonts/axisregistry/commit/0d876c2f0c692535f47d13825aadd21003596b1b):

![image](https://github.com/googlefonts/axisregistry/assets/213676/d0088f69-e28f-46fe-a599-47b65f7f412f)
